let mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . f 4 4 f f f f . . . . . . 
    . . f 4 5 5 4 5 f b f f . . . . 
    . . f 5 5 5 5 4 e 3 3 b f . . . 
    . . f e 4 4 4 e 3 3 3 3 b f . . 
    . f 3 3 3 3 3 3 3 3 3 3 3 f . . 
    . f 3 3 e e 3 b e 3 3 3 3 f . . 
    . f 3 3 e e e f f 3 3 3 3 f . . 
    . . f e e e f b f b b b b f f . 
    . . . e 4 4 f 1 e b b b b b f . 
    . . . f 4 4 4 4 f b b b b b f . 
    . . . f d d d e 4 4 b b b f . . 
    . . . f d d d e 4 4 f f f . . . 
    . . f d d d b b e e b b f . . . 
    . . f b d 1 d 1 d d b f . . . . 
    . . . f f f b b f f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
let myEnemy = sprites.create(img`
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f1111111dbf......
    ......fd1111111ddf......
    ......fd111111dddf......
    ......fd111ddddddf......
    ......fd111ddddddf......
    ......fd1dddddddbf......
    ......fd1dfbddbbff......
    ......fbddfcdbbcf.......
    .....ffffccddbfff.......
    ....fcb1bbbfcffff.......
    ....f1b1dcffffffff......
    ....fdfdf..ffffffffff...
    .....f.f.....ffffff.....
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
myEnemy.follow(mySprite)
myEnemy.setPosition(151, 0)
